#!/bin/dash

cd  "build/"
ghc "Hsxx.hs" -o "hsxx" || exit 4

cd "../sxx/"
echo "testing all files in sxx/ ..."

for filename in *.sxx ; do
    echo "$filename"
#     echo "compare with: .output.$filename"
    if [ -f ".input.$filename" ] ; then
        ../build/hsxx "$filename" < ".input.$filename" | \
            awk '/beginning execution --------------------/,0' | \
            diff ".output.$filename" - || exit 1
    else
        ../build/hsxx "$filename" | \
            awk '/beginning execution --------------------/,0' | \
            diff ".output.$filename" - || exit 1
    fi

done

echo "OK :~)"
