#!/bin/dash

cd "sxxl/"
echo "testing all files in sxxl/ ..."

for filename in *.out ; do
    echo "$filename"
    sxxl "$filename" > "/tmp/bcm.test.sxx"
    if [ -f ".input.$filename" ] ; then
        sxx "/tmp/bcm.test.sxx" < ".input.$filename" > "/tmp/bcm.test.result" 2>&1
    else
        sxx "/tmp/bcm.test.sxx" > "/tmp/bcm.test.result" 2>&1
    fi
    tail -n +2 ".output.$filename" > "/tmp/bcm.test.output"
    diff "/tmp/bcm.test.result" "/tmp/bcm.test.output"  || exit 1
done

echo "OK :~)"
