#!/usr/bin/dash

cd  "../src/"
# ghc "../src/hsxx.hs" || exit 2
ghc "Hsxx.hs" -outputdir "../test/build" -o "../test/build/hsxx" || exit 2

cd "../test/sxx/"
echo "testing all files in sxx/ ..."

# for filename in $(ls -1 "dantest/*.sxx") ; do
# for filename in dantest/*.sxx ; do
# cd "sxx/"
for filename in *.sxx ; do
    echo "$filename"
#     echo "compare with: .output.$filename"
    if [ -f ".input.$filename" ] ; then
        ../build/hsxx "$filename" < ".input.$filename" | \
            awk '/beginning execution --------------------/,0' | \
            diff ".output.$filename" - || exit 1
    else
        ../build/hsxx "$filename" | \
            awk '/beginning execution --------------------/,0' | \
            diff ".output.$filename" - || exit 1
    fi

done

echo "OK :~)"
