#!/usr/bin/dash

ghc "hsxx.hs"

echo "testing all files in dantest/ ..."

# for filename in $(ls -1 "dantest/*.sxx") ; do
# for filename in dantest/*.sxx ; do
cd "dantest/"
for filename in *.sxx ; do
    echo "$filename"
#     echo "compare with: .output.$filename"
    ../hsxx "$filename" \
        | awk '/beginning execution --------------------/,0' \
        | diff ".output.$filename" - \
        || exit 1
done

echo "OK :~)"
